default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-added-large-files

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          - --verbose
          - feat
          - fix
          - docs
          - refactor
          - test
          - ci
          - build
          - chore

  - repo: local
    hooks:
      - id: actionlint
        name: actionlint
        entry: actionlint
        language: system
        files: ^\.github/workflows/.*\.ya?ml$

      - id: gitleaks
        name: gitleaks
        entry: gitleaks dir --redact --no-banner .
        language: system
        pass_filenames: false

      - id: markdownlint
        name: markdownlint
        entry: markdownlint-cli2
        language: system
        types:
          - markdown

      - id: nix-fmt
        name: nix fmt
        entry: nix fmt -- flake.nix
        language: system
        pass_filenames: false
        files: ^flake\.nix$

      - id: go-fmt
        name: go fmt
        entry: gofmt -w
        language: system
        types: [go]
